version: 2.1

workflows:
  sample:
    jobs:
      - build-and-test:
  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - circle-project-setup
    jobs:
      - deploy


jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.6.2

    steps:
      - checkout
      - run:
          name: Installing the dependencies
          command: |
            sudo apt-get -y -qq update
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            
      - run:
          name: Installing the Node manager
          command: |
            npm install aws-cdk@1.115.0
            npm --version
      - run:
          name: installing the requirements.
          command: |
            python3 -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt

  deploy:
    docker:
      - image: cimg/node:16.6.2
      
    steps:
      - checkout
      - run:
          name: run hello world
          command: echo "hello world"




