version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  sample:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - circleci-project-setup


jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.6.2

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Installing the Node manager
          command: npm install aws-cdk@1.115.0
      - run:
          name: installing the requirements.
          command: |
            python3 -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt



