version: 2.1

workflows:
  sample:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - circleci-project-setup


jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.6.2

    steps:
      - checkout
      - run:
          name: Installing the dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt install python3.8
            sudo apt install python3-pip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            
      - run:
          name: Installing the Node manager
          command: npm install aws-cdk@1.115.0
      - run:
          name: installing the requirements.
          command: |
            ls
            cd cdk-sample/
            python3 -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt



